### PR TITLE
Update dev bits

### PR DESCRIPTION
**Pull request by weshooper**
- Update dev dependencies (and a few minor tweaks to accommodate)
- Require a [supported version of PHP](https://secure.php.net/supported-versions.php) (and configure CI to build with 7.2 and 7.3)
- Remove redundant field in `composer.json` (and add recommended fields)

### CODE REVIEW

**Comment by weshooper** [comment]
Tests were failing before, help here appreciated @fusionspim/devs please! 🤕

**Comment by maxakropolis** [comment]
I think this is failing because it features PHPUnit filenames and line numbers in the fixture, which will obviously have changed as the version has changed.

**Comment by ziadoz** [comment]
@weshooper @maxakropolis is correct, it's the line numbers in the fixtures by the looks of it. I've adjusted them.

**Comment by ziadoz** [comment]
There's another error here, but I can't suss it at the moment as it isn't occurring locally.

**Pull request merged**
